services:
  x5-ner:
    build: .
    image: x5-ner:local
    environment:
      - ARTIFACTS_DIR=/app/artifacts/rubert-base-cased/20250930-165530
      - X5_FORCE_DEVICE=cpu
      - TOKENIZERS_PARALLELISM=false
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - TORCH_NUM_THREADS=1
      - TORCH_NUM_INTEROP_THREADS=1
      - HOST=0.0.0.0
      - PORT=8000
      - GUNICORN_WORKERS=4 # tune per CPU/GPU
      - GUNICORN_PRELOAD_APP=true
      - GUNICORN_LOGLEVEL=warning
      - MICRO_BATCH_ENABLED=true
      - MICRO_BATCH_MAX_SIZE=32
      - MICRO_BATCH_MAX_WAIT_MS=3
      - MICRO_BATCH_HARD_TIMEOUT_MS=500
      - GUNICORN_MAX_REQUESTS=5500
      - GUNICORN_MAX_REQUESTS_JITTER=0
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health | grep -q 'ok'"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
