services:
  x5-ner:
    build: .
    image: x5-ner:local
    environment:
      - TZ=Europe/Moscow
      # - ARTIFACTS_DIR=/app/artifacts/rubert-base-cased/20250930_165530
      # - ARTIFACTS_DIR=/app/artifacts/rubert_base_cased_20251002-111705
      - ARTIFACTS_DIR=/app/artifacts/rubert-base-cased/20251002-111705
      - X5_FORCE_DEVICE=cpu
      - TOKENIZERS_PARALLELISM=false
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - TORCH_NUM_THREADS=1
      - TORCH_NUM_INTEROP_THREADS=1
      - PREDICT_MAX_CONCURRENCY=1
      - HOST=0.0.0.0
      - PORT=8000
      - GUNICORN_WORKERS=8 # tuned for 8 CPU
      - GUNICORN_PRELOAD_APP=true
      - GUNICORN_LOGLEVEL=warning
      - MICRO_BATCH_ENABLED=true
      - MICRO_BATCH_MAX_SIZE=16
      - MICRO_BATCH_MAX_WAIT_MS=6
      - MICRO_BATCH_HARD_TIMEOUT_MS=1200
      - MICRO_BATCH_QUEUE_MAXSIZE=1024
      - CACHE_ENABLED=true
      - CACHE_MAX_SIZE=20000
      - CACHE_TTL_SECONDS=7200
      - GUNICORN_TIMEOUT=15
      - GUNICORN_KEEPALIVE=5
      - GUNICORN_MAX_REQUESTS=5500
      - GUNICORN_MAX_REQUESTS_JITTER=0
    ports:
      - "8000:8000"
    volumes:
      - ./artifacts:/app/artifacts:ro
    restart: on-failure
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8000/health | grep -q 'ok'"]
      interval: 60s
      timeout: 3s
      retries: 3
      start_period: 30s
    networks:
        - x5-network

networks:
  x5-network:
    driver: bridge
