name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint & type check
        run: |
          black --check .
          isort --check-only .
          flake8 .
          mypy service
      - name: Tests
        run: |
          pytest -q
      - name: Note
        run: echo "Tag verified. Attach artifacts manually as per docs/ARTIFACTS.md."
